all: ej1 ej2 ej3 ej5

cflags=-lX11 -lm -lpthread -lfftw3

ej1: ej1.cpp
	g++ $(cflags) ej1.cpp -o ej1

ej2: ej2.cpp
	g++ $(cflags) ej2.cpp -o ej2

ej3: ej3.cpp
	g++ $(cflags) ej3.cpp -o ej3

ej5: ej5.cpp
	g++ $(cflags) ej5.cpp -o ej5
