all: ej1 ej1_5 ej2 ej3

ej1: ej1.cpp
	g++ -lX11 -lm -lpthread ej1.cpp -o ej1  

ej1_5: ej1_5.cpp
	g++ -lX11 -lm -lpthread ej1_5.cpp -o ej1_5  

ej2: ej2.cpp
	g++ -lX11 -lm -lpthread ej2.cpp -o ej2  

ej3: ej3.cpp
	g++ -lX11 -lm -lpthread ej3.cpp -o ej3  

