all: ej1 ej2 #ej3 ej3_2 ej4 ej5 ej6

ej1: ej1.cpp
	g++ -lX11 -lm -lpthread ej1.cpp -o ej1  

ej2: ej2.cpp
	g++ -lX11 -lm -lpthread ej2.cpp -o ej2  

# ej3: ej3.cpp
# 	g++ -lX11 -lm -lpthread ej3.cpp -o ej3  

# ej3_2: ej3_2.cpp
# 	g++ -lX11 -lm -lpthread ej3_2.cpp -o ej3_2  

# ej4: ej4.cpp
# 	g++ -lX11 -lm -lpthread ej4.cpp -o ej4  

# ej5: ej5.cpp
# 	g++ -lX11 -lm -lpthread ej5.cpp -o ej5  

# ej6: ej6.cpp
# 	g++ -lX11 -lm -lpthread ej6.cpp -o ej6  
